# ReadTheDocs build configuration
version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Install your package and documentation dependencies
    - pip install -e .
    - pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints numpydoc

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Output formats
formats:
  - html

