version: 2

# Build environment
build:
  os: ubuntu-22.04
  # This command satisfies the validator without
  # interfering with the conda build.
  commands:
    - "/bin/true"

# Use your conda environment file
conda:
  environment: dolphindes.yml

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Optional formats
formats:
  - htmlzip
