version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"  # Match the Python version from your .yml file

# Use your conda environment file
conda:
  environment: dolphindes.yml

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Optional formats
formats:
  - htmlzip
