version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Install dependencies using pip
python:
  install:
    - requirements: docs/requirements.txt  # Or your main requirements file
    - path: .                           # This will now work

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
