version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Use your conda environment
conda:
  environment: dolphindes.yml

# Install your package in editable mode
python:
  install:
    - method: pip
      path: .
      editable: true

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Output formats (optional)
formats:
  - htmlzip   # default HTML build is automatic
  # - pdf
  # - epub

