version: 2

# Build environment
build:
  os: ubuntu-22.04
  commands: [] 

# Use your conda environment file
conda:
  environment: dolphindes.yml

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Optional formats
formats:
  - htmlzip
