version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Use your conda environment
conda:
  environment: dolphindes.yml

# Additional commands after conda environment is ready
commands:
  # Install your package in editable mode so autodoc can import it
  - pip install -e .

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Output formats (optional, only if you want PDF or EPUB)
formats:
  - htmlzip   # zip of HTML docs
  # - pdf
  # - epub

